 
server:
  port: 8084
spring:
  application:
    name: category-service
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"